# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=5)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qs', models.PositiveSmallIntegerField()),
                ('calcs_allowed', models.BooleanField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paper')),
            ],
        ),
    ]
