# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks_breakdown',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='new_section',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='total_marks',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
